### ISSUE TITLE
Changer l'input datetime-local pour les formulaires

### ISSUE THREAD

**Issue by fbdb** [Zegorax/MentorArc#21]
Actuellement nous utilisons un input datetime-local, qui, je cite, [selon la doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local):

*at the moment support is patchy, with only Chrome/Opera and Edge on desktop and most modern versions of mobile browsers having usable implementations. In other browsers, these degrade gracefully to simple \<input type="text"\> controls.*.

En gros c'est de la m si t'es pas sur chrome, opéra ou edge. L'input est un simple type text. Trouver autre chose qui permette donc à l'utilisateur de rentrer facilement une date et une heure pour les formulaires.

firefox ftw

**Comment by RoxaneCarraux** [comment]
Materialize possède deux pickers, un datepicker et un timepicker. doc ici : https://materializecss.com/pickers.html  J'ai donc mis cela en place dans les formulaires

Il y avait également bootstrap qui possède également des datetimepicker, par exemple cet exemple  fait ce que nous voulions : https://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers, mais le mélange entre bootstrap et materialize pose problème et n'est certainement pas une bonne idée. C'est pour cela que je me suis tournée vers la première solution.
